### ISSUE TITLE
Use a date picker component for the event date

### ISSUE THREAD

**Issue by freemanT** [McPringle/sportchef#115]
Find a Polymer-plugin that shows a date-picking-dialog with date input fields.
Integrate it at the date-field in event-registration-section in the administration interface.

It should be possible to fill a date-field by picking it from a calendar-dialog.

**Comment by McPringle** [comment]
@freemanT is working on this issue.

**Comment by McPringle** [comment]
@freemanT, you should take a look at the [Vaadin Elements](https://vaadin.com/elements/-/element/vaadin-date-picker)!
