### ISSUE TITLE
Implement color threshold for event images

### ISSUE THREAD

**Issue by McPringle** [McPringle/sportchef#127]
A bright image results in a bright background color. The white text is hard to read or invisible.

**Comment by PReimers** [comment]
We have to discus if we want to change the font-color or if we just want to limit it to a "lowest" color.

**Comment by PReimers** [comment]
@Interactiondesigner also suggested to limit it to a "lowest" background color

**Comment by McPringle** [comment]
Ok, let's implement it this way.
