### ISSUE TITLE
Create the design for the login dialog

### ISSUE THREAD

**Issue by McPringle** [McPringle/sportchef#147]
How the login process works:
---
Step 1: Klick on "Login" button to open a dialog
Step 2: Enter email address and request a one time code
Step 3: Check email for one time code
Step 4: Enter one time code in login dialog or click on link in email to finish login process

**Comment by Interactiondesigner** [comment]
The login dialog … here we go:
![login_dialog-06](https://cloud.githubusercontent.com/assets/17220369/13509363/52681d4c-e18b-11e5-9a1c-ce7a9e9231ba.png)
