### ISSUE TITLE
Install SportChef in a production environment

### ISSUE THREAD

**Issue by McPringle** [McPringle/sportchef#149]
On an own server? In a cloud? Which cloud? Should we use Docker?

**Comment by PReimers** [comment]
Docker :+1:

**Comment by McPringle** [comment]
Let's do it! I'm on the train to Hackergarten Basel now…

**Comment by McPringle** [comment]
**The Docker image of _SportChef_ is available on [Docker Hub](https://hub.docker.com/r/mcpringle/sportchef/)!**
Now we have to collect informations about all the Docker providers out there, pros and cons, to decide how to continue. We don't need a mail server there but we must be able to use our own domain name! The hosting has not to be free, I'm willing to pay for it.

**Comment by McPringle** [comment]
I created an account for the [Swisscom Cloud](http://developer.swisscom.com/) but the documentation is actually a little bit behind. I'm waiting for an updated documentation that covers the part of running a docker container.
