### ISSUE TITLE
Write Release Notes

### ISSUE THREAD

**Issue by McPringle** [McPringle/sportchef#182]

**Comment by PReimers** [comment]
@McPringle should the release notes be separated in a own file (changelog.md)

**Comment by McPringle** [comment]
I like it to be visible directly on the project page. When we create an own website for the project (e.g. with [GitHub Pages](https://pages.github.com)), then we can move the release notes to an own file and include it on the website (e.g. with the [marked-element](https://elements.polymer-project.org/elements/marked-element) component).

**Comment by PReimers** [comment]
Personally I hate it if the readme is endless.
But the GH-Page is a nice idea ;)

**Comment by McPringle** [comment]
#207 :-)

**Comment by PReimers** [comment]
HaHa, haven't seen the issue :D
