### ISSUE TITLE
Design a user profile page

### ISSUE THREAD

**Issue by McPringle** [McPringle/sportchef#266]
First version should be very basic:
- name
- email
- phone

**Comment by Interactiondesigner** [comment]
Here we go:
![20160505_userprofil](https://cloud.githubusercontent.com/assets/17220369/15055441/ee0eea84-130c-11e6-9048-177e8b0cb044.png)

**Comment by Interactiondesigner** [comment]
... and here is the profil with a user pic by gravatar:
![20160505_userprofil_with_pic](https://cloud.githubusercontent.com/assets/17220369/15055872/340725d6-130f-11e6-920a-ecacb4a35f21.png)

**Comment by PReimers** [comment]
@McPringle do you prefer a particular Gravatar rating?

**Comment by McPringle** [comment]
@PReimers:
We should only use images rated _G_ because we have children on our site:
_A G rated gravatar is suitable for display on all websites with any audience type._
