### ISSUE TITLE
Home Page is down :(

### ISSUE THREAD

**Issue by EmaSuriano** [McPringle/sportchef#305]
Hello, I wanted to check what is the project about but the homepage seems to be down :(

This is the link I'm using --> https://www.sportchef.ch/

**Comment by McPringle** [comment]
Hi @EmaSuriano 

I'm really sorry, but this project is dead. The original developer and his friends lost interest on this project and I can't handle this as a one-person-project. The website was taken offline to avoid paying money for a dead project. If you want, please feel free to fork this project and continue the work!
