### ISSUE TITLE
Implement passwordless authentication

### ISSUE THREAD

**Issue by McPringle** [McPringle/sportchef#36]
Read [Why Passwordless Authentication Works](http://www.sitepoint.com/passwordless-authentication-works/) beforehand

**Comment by McPringle** [comment]
It's very important to protect the admin area!

**Comment by McPringle** [comment]
@PReimers is working on the authentication.
@McPringle will do the authorization last week of Dec 2015.

**Comment by PReimers** [comment]
Authentication is working..
Authentication-Tests are still missing
I'l work on them in the next days.

**Comment by McPringle** [comment]
A huge thank you to @PReimers for his work and contribution on PR #90 which was very useful in solving this issue!
