### ISSUE TITLE
Form to enter an event should provide an image upload

### ISSUE THREAD

**Issue by McPringle** [McPringle/sportchef#42]

**Comment by PReimers** [comment]
Does the server accept an image?
And how should it be transmitted?

**Comment by McPringle** [comment]
The server side has to be modified, too. Actually it doesn't accept an image. I hope to get some answers this Thursday at the Hackergarten in Basel (Ixchel knows Polymer a lot better than we do, she will be at the Hackergarten and would like to help us).
