### ISSUE TITLE
Updating conflicting events does not fail

### ISSUE THREAD

**Issue by McPringle** [McPringle/sportchef#46]
- user a reads an event in actual version
- user b reads the same event in the same, actual version
- user a modifies location and can successfully save (ok)
- user b modifies the title and can successfully save (not ok)

The modified location of user a is lost (overwritten by user b). Instead of a successful save of user b I expect a conflict (`OptimisticLockException` on the server side and HTTP status code `409` on the client side). Tested by `EventResourceIT` line 59.

**Comment by McPringle** [comment]
Hi @jarekratajski, do you have a good idea how we can handle that? Should this be done by airomem/prevalayer like JPA does or should we handle that in SportChef itself?

**Comment by jarekratajski** [comment]
So far  I have one solution that I like: 
make Event immutable and solve problem on container (Map or Reference).


I can do this.

**Comment by McPringle** [comment]
Nice idea. I like immutable objects. Yesterday I thought that I can now make `Event` and `User` immutable because we replaced JPA with Airomem.

**Comment by McPringle** [comment]
User (#64) and Event (#63) classes are now immutable.

**Comment by McPringle** [comment]
Don't forget to activate the tests in EventResourceIT and UserResourceIT!
