### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by CoalaJoe** [McPringle/sportchef#52]
We have still problems with the translations. The easiest and best option would be server-side translations; templates that are generated when polymer whats to load them.

**Comment by PReimers** [comment]
I think it relates to #30

I've tried to implement the translation with https://ebidel.github.io/i18n-msg/components/i18n-msg
But it seem to be impossible to translate within polymer (IMO)

**Comment by McPringle** [comment]
Duplicate with #30 
We'll take a look at localization later on.
