### ISSUE TITLE
Extract jQuery web component into a separate project

### ISSUE THREAD

**Issue by McPringle** [McPringle/sportchef#60]

**Comment by victorparmar** [comment]
You can actually pull the entire front-end out as a separate project. Is this what this issue is about?

**Comment by McPringle** [comment]
Nope. This issue is about to provide the jQuery web component "to the world" :-) so it can be used from everyone.

**Comment by McPringle** [comment]
I decided not to create a separate project for jQuery as a WebComponent. If you have a different opinion, please comment.
