### ISSUE TITLE
Build error on win7x64

### ISSUE THREAD

**Issue by syzer** [McPringle/sportchef#62]
after `gradle build`:

```
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:startScripts FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':startScripts'.
> No value has been specified for property 'mainClassName'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info
or                                                              --debug
option to get more log output.

BUILD FAILED

Total time: 13.278 secs
```

**Comment by McPringle** [comment]
I'm setting up a windows 7 environment to reproduce the reported problem.

**Comment by McPringle** [comment]
Hi @syzer

I can't reproduce your problem in Windows 7 Professional 64 Bit. This is clean install of Windows, git and Java 8. I cloned to repository using the git bash and started the build using the PowerShell. The build finished successfully.

Maybe you have a gradle installation somewhere on your path and you used ```gradle build```? On Windows you have to use ```gradlew build``` to start the build. ```gradlew``` is a batch script in the root directory of the project.

Can you please start the build using ```gradlew build``` (if your actual directory is not in your path, you have to use ```.\gradlew build```) and report here, if it finished successfully or not? If not, can you please provide more information (which shell do you use)?

cu
@McPringle

**Comment by McPringle** [comment]
Not reproducible on four different Windows 7 (64 bit) computers. Please update your fork and try to build again. If your problem persists, please reopen this issue and provide more information on how you started the build and include the complete build output (don't forget the logs and reports).

**Comment by syzer** [comment]
thanks!
