### ISSUE TITLE
Write a test to check if a PUT can be misused to create a new user

### ISSUE THREAD

**Issue by McPringle** [McPringle/sportchef#77]

**Comment by freemanT** [comment]
Problem reproduced on May 7th. If you make a PUT-call on /api/user/[id] and your request-params contain an (existing) userid, then the existing user is updated.

**Comment by freemanT** [comment]
or a new user is created.

**Comment by McPringle** [comment]
I created a test to reproduce the reported error. Fix #79 is in progress.
